---

# Archive/backup the current website to an archive directory on WINDOWS server

# The following variables need to be provided via the commandline:
#   OLD_VERSION - The version to be backed up and replaced.

- name: Archive the current website
  hosts: web_hosts
  gather_facts: no
  vars:
    _ARCHIVE_FILE_NAME: '{{ OLD_VERSION }}_BACKUP.7z'
  vars_files:
    - ../group_vars/vars/deployment_vars.yaml
    - ../../OS/windows/vars/zip_utility.yaml

  tasks:
  # ----------------------------------------------------------------------------------------
  # Display the OLD_VERSION variable (provided by CLI)
  # ----------------------------------------------------------------------------------------
  - debug:
      msg:
      - 'OLD_VERSION: {{ OLD_VERSION }}'
      - 'ARCHIVE_FILE_NAME: {{ _ARCHIVE_FILE_NAME }}'

  # ----------------------------------------------------------------------------------------
  # Create a non-destructive ZIP archive of the existing website
  # ----------------------------------------------------------------------------------------
  - name: Archive the existing website directory
    win_shell: 'cmd /c "{{ ZIP_EXECUTABLE }}" a -bd -mx9 -r {{ _ARCHIVE_FILE_NAME }} *'
    args:
      chdir: '{{ WEB_WEBSITES_DIR }}'
    register: _ARCHIVE_ZIP

  # ----------------------------------------------------------------------------------------
  # Display the results of the zipping process
  # ----------------------------------------------------------------------------------------
  - debug:
      msg:
      - 'CMD: {{ _ARCHIVE_ZIP.cmd }}'
      - 'ZIP ELASPED TIME: {{ _ARCHIVE_ZIP.delta }}'
      - '{{ _ARCHIVE_ZIP.stdout_lines }}'

  # ----------------------------------------------------------------------------------------
  # Get the stat info about the file, to verify the integrity after copying.
  # ----------------------------------------------------------------------------------------
  - name: Get the stat info about the ZIP file
    win_stat:
      path: '{{ WEB_WEBSITES_DIR }}\{{ _ARCHIVE_FILE_NAME }}'
    register: _ARCHIVE_SRC_FILE_STAT

  # ----------------------------------------------------------------------------------------
  # Check the file size, to make sure it has the correct minimum size, otherwise FAIL.
  # It should not be an empty zip file, or have substantially less content than expected.
  # ----------------------------------------------------------------------------------------
  - name: Check that the ZIP file is populated (based on size).
    fail:
      msg: |
       ZIP file did not meet the minimum requirements for size.
       Please check the zip file contents '{{WEB_WEBSITES_DIR}}\{{ _ARCHIVE_FILE_NAME }}'.
       EXPECTED Min File Size: {{ WEB_ZIP_MIN_SIZE_BYTES }} bytes.
       ACTUAL File Size: {{ _ARCHIVE_SRC_FILE_STAT.stat.size }} bytes.
    when:
      - _ARCHIVE_SRC_FILE_STAT.stat.size < WEB_ZIP_MIN_SIZE_BYTES

  # ----------------------------------------------------------------------------------------
  # Copy the Zip file to the target ARCHIVE directory
  # ----------------------------------------------------------------------------------------
  - name: Copy Archive File to Archive Directory
    win_copy:
      src: '{{ WEB_WEBSITES_DIR }}\{{ _ARCHIVE_FILE_NAME }}'
      dest: '{{ WEB_ARCHIVE_DIR }}\{{ _ARCHIVE_FILE_NAME }}'
      backup: no
      remote_src: yes

  # ----------------------------------------------------------------------------------------
  # Get the file stat information about the copied file
  # ----------------------------------------------------------------------------------------
  - name: Get file stat info about COPIED archive file
    win_stat:
      path: '{{ WEB_ARCHIVE_DIR }}\{{ _ARCHIVE_FILE_NAME }}'
    register: _ARCHIVE_COPY_FILE_STAT

  # ----------------------------------------------------------------------------------------
  # Unable to delete the file due to file missing or checksums do no match
  # so fail the playbook
  # ----------------------------------------------------------------------------------------
  - name: Fail the copy process if the src archive file does not exactly match the dest file
    fail:
      msg: |
        'COPIED Archive File exists: {{ _ARCHIVE_COPY_FILE_STAT.stat.exists }}'
        'SOURCE Archive Checksum: {{ _ARCHIVE_SRC_FILE_STAT.stat.checksum }}'
        'COPIED Archive Checksum: {{ _ARCHIVE_COPY_FILE_STAT.stat.checksum }}'
    when: not _ARCHIVE_COPY_FILE_STAT.stat.exists or
      _ARCHIVE_COPY_FILE_STAT.stat.checksum != _ARCHIVE_SRC_FILE_STAT.stat.checksum


  # ==================
  #  CLEAN UP
  # ==================

  # ----------------------------------------------------------------------------------------
  # Delete the original (src) zip file if the dest zip file exists and
  # the checksums are the same
  # ----------------------------------------------------------------------------------------
  - name: Delete source zip archive file
    win_file:
      path: '{{ WEB_WEBSITES_DIR }}\{{ _ARCHIVE_FILE_NAME }}'
      state: absent

  # ---------------------------------------------------------------------------------------
  # Delete the backed up content, now that the content has been zipped, archived
  # and validated.
  # ---------------------------------------------------------------------------------------
  - name: Delete web content that was archived and backed up.
    win_file:
      path: '{{ WEB_WEBSITES_SITE_DIR }}'
      state: absent

...

